/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tela;

import javax.swing.JOptionPane;
import negocio.Celular;
import negocio.ContaCelular;

/**
 *
 * @author luis.dutra
 */
public class FrmTela extends javax.swing.JFrame {

    // Celular 1 - conta principal
    Celular celular1 = new Celular();
    ContaCelular conta1 = new ContaCelular();

    // Celular 2 e Celular 3 - contatos
    Celular celular2 = new Celular();
    ContaCelular conta2 = new ContaCelular();

    Celular celular3 = new Celular();
    ContaCelular conta3 = new ContaCelular();

    /**
     * Creates new form FrmTela
     */
    public FrmTela() {
        initComponents();
        BtnSair.setVisible(false);
        BtnEntrar.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        PlPrincipal = new javax.swing.JTabbedPane();
        TpConsumo = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        LbConsumoTotal = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        LbChamadaLocal = new javax.swing.JLabel();
        LbChamadaEstadual = new javax.swing.JLabel();
        LbChamadaInterEstado = new javax.swing.JLabel();
        LbSms = new javax.swing.JLabel();
        LbInternet = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        LbBitcallsTransferidos = new javax.swing.JLabel();
        TpRecarregar = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        Btn10 = new javax.swing.JButton();
        Btn15 = new javax.swing.JButton();
        Btn25 = new javax.swing.JButton();
        Btn50 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        TpServicos = new javax.swing.JPanel();
        BtnChamadaDDDEstado = new javax.swing.JButton();
        BtnChamadaDDDEstadoFora = new javax.swing.JButton();
        BtnChamada = new javax.swing.JButton();
        BtnSms = new javax.swing.JButton();
        BtnInternet = new javax.swing.JButton();
        TpTransferir = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        LbContato2 = new javax.swing.JLabel();
        LbContato3 = new javax.swing.JLabel();
        RdContato2 = new javax.swing.JRadioButton();
        RdContato3 = new javax.swing.JRadioButton();
        jLabel17 = new javax.swing.JLabel();
        Tfdtransferir = new javax.swing.JTextField();
        BtnConfirmaTransferir = new javax.swing.JButton();
        BtnServicos = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        BtnEntrar = new javax.swing.JButton();
        BtnSair = new javax.swing.JButton();
        LbSaldo = new javax.swing.JLabel();
        BtnRecarregar = new javax.swing.JButton();
        BtnConsumo = new javax.swing.JButton();
        BtnTransferir = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        LbNome = new javax.swing.JLabel();
        LbNumero = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new java.awt.GridLayout(1, 0));
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 835, -1));

        PlPrincipal.setTabPlacement(javax.swing.JTabbedPane.LEFT);

        TpConsumo.setToolTipText("");
        TpConsumo.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setText("Consumo total de Bitcalls:");

        jLabel4.setText("Chamadas locais realizadas:");

        jLabel9.setText("Chamadas DDD estaduais realizadas:");

        jLabel10.setText("Chamadas DDD para fora do estado realizadas:");

        jLabel11.setText("SMS enviados:");

        jLabel12.setText("Internet 4G utilizada:");

        jLabel18.setText("Bitcalls transferidos:");

        javax.swing.GroupLayout TpConsumoLayout = new javax.swing.GroupLayout(TpConsumo);
        TpConsumo.setLayout(TpConsumoLayout);
        TpConsumoLayout.setHorizontalGroup(
            TpConsumoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TpConsumoLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(TpConsumoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TpConsumoLayout.createSequentialGroup()
                        .addGroup(TpConsumoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(TpConsumoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LbChamadaInterEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LbChamadaEstadual, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LbSms, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LbInternet, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(TpConsumoLayout.createSequentialGroup()
                        .addGroup(TpConsumoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(TpConsumoLayout.createSequentialGroup()
                                .addGroup(TpConsumoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel18)
                                    .addComponent(jLabel4))
                                .addGap(270, 270, 270)
                                .addGroup(TpConsumoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(LbBitcallsTransferidos, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                                    .addComponent(LbChamadaLocal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(TpConsumoLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(249, 249, 249)
                                .addComponent(LbConsumoTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 1, Short.MAX_VALUE)))
                .addContainerGap(251, Short.MAX_VALUE))
        );
        TpConsumoLayout.setVerticalGroup(
            TpConsumoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TpConsumoLayout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addGroup(TpConsumoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(LbConsumoTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(73, 73, 73)
                .addGroup(TpConsumoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18)
                    .addComponent(LbBitcallsTransferidos, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(TpConsumoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(LbChamadaLocal, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(TpConsumoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(LbChamadaEstadual, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(TpConsumoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(LbChamadaInterEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(TpConsumoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(LbSms, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(TpConsumoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(LbInternet, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(106, Short.MAX_VALUE))
        );

        PlPrincipal.addTab("TpCon", TpConsumo);

        jLabel2.setText("Quantos Bitcalls deseja recarregar?");

        Btn10.setText("R$ 10,00");
        Btn10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn10ActionPerformed(evt);
            }
        });

        Btn15.setText("R$ 15,00");
        Btn15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn15ActionPerformed(evt);
            }
        });

        Btn25.setText("R$ 25,00");
        Btn25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn25ActionPerformed(evt);
            }
        });

        Btn50.setText("R$ 50,00");
        Btn50.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn50ActionPerformed(evt);
            }
        });

        jLabel5.setText("10 Bitcalls");

        jLabel6.setText("15 Bitcalls");

        jLabel7.setText("25 Bitcalls");

        jLabel8.setText("10 Bitcalls");

        javax.swing.GroupLayout TpRecarregarLayout = new javax.swing.GroupLayout(TpRecarregar);
        TpRecarregar.setLayout(TpRecarregarLayout);
        TpRecarregarLayout.setHorizontalGroup(
            TpRecarregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TpRecarregarLayout.createSequentialGroup()
                .addGroup(TpRecarregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TpRecarregarLayout.createSequentialGroup()
                        .addGap(242, 242, 242)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(TpRecarregarLayout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addGroup(TpRecarregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Btn15)
                            .addComponent(Btn10)
                            .addComponent(Btn25)
                            .addComponent(Btn50))
                        .addGap(52, 52, 52)
                        .addGroup(TpRecarregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))))
                .addContainerGap(317, Short.MAX_VALUE))
        );
        TpRecarregarLayout.setVerticalGroup(
            TpRecarregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TpRecarregarLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76)
                .addGroup(TpRecarregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Btn10)
                    .addComponent(jLabel5))
                .addGap(34, 34, 34)
                .addGroup(TpRecarregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Btn15)
                    .addComponent(jLabel6))
                .addGap(34, 34, 34)
                .addGroup(TpRecarregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Btn25)
                    .addComponent(jLabel7))
                .addGap(34, 34, 34)
                .addGroup(TpRecarregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Btn50)
                    .addComponent(jLabel8))
                .addContainerGap(239, Short.MAX_VALUE))
        );

        PlPrincipal.addTab("TpRec", TpRecarregar);

        BtnChamadaDDDEstado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tela/ligar.png"))); // NOI18N
        BtnChamadaDDDEstado.setText("Chamada de longa distância DDD dentro do estado");
        BtnChamadaDDDEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnChamadaDDDEstadoActionPerformed(evt);
            }
        });

        BtnChamadaDDDEstadoFora.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tela/ligar.png"))); // NOI18N
        BtnChamadaDDDEstadoFora.setText("Chamada de longa distância DDD para fora do estado");
        BtnChamadaDDDEstadoFora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnChamadaDDDEstadoForaActionPerformed(evt);
            }
        });

        BtnChamada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tela/ligar.png"))); // NOI18N
        BtnChamada.setText("Chamada Local");
        BtnChamada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnChamadaActionPerformed(evt);
            }
        });

        BtnSms.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tela/sms.png"))); // NOI18N
        BtnSms.setText("Envio de SMS");
        BtnSms.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSmsActionPerformed(evt);
            }
        });

        BtnInternet.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tela/Internet2.png"))); // NOI18N
        BtnInternet.setText("Um dia completo de Internet 4G");
        BtnInternet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnInternetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout TpServicosLayout = new javax.swing.GroupLayout(TpServicos);
        TpServicos.setLayout(TpServicosLayout);
        TpServicosLayout.setHorizontalGroup(
            TpServicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TpServicosLayout.createSequentialGroup()
                .addGap(114, 114, 114)
                .addGroup(TpServicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BtnChamada, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnChamadaDDDEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnChamadaDDDEstadoFora, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnSms, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnInternet, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(382, Short.MAX_VALUE))
        );
        TpServicosLayout.setVerticalGroup(
            TpServicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TpServicosLayout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(BtnChamada, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtnChamadaDDDEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtnChamadaDDDEstadoFora, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtnSms, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtnInternet, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(270, Short.MAX_VALUE))
        );

        PlPrincipal.addTab("TpSer", TpServicos);

        jLabel15.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel15.setText("Contatos");

        jLabel17.setText("Quantos Bitcalls você deseja transferir:");

        BtnConfirmaTransferir.setText("Transferir");
        BtnConfirmaTransferir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnConfirmaTransferirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout TpTransferirLayout = new javax.swing.GroupLayout(TpTransferir);
        TpTransferir.setLayout(TpTransferirLayout);
        TpTransferirLayout.setHorizontalGroup(
            TpTransferirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TpTransferirLayout.createSequentialGroup()
                .addGroup(TpTransferirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TpTransferirLayout.createSequentialGroup()
                        .addGap(266, 266, 266)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(TpTransferirLayout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addGroup(TpTransferirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(BtnConfirmaTransferir)
                            .addGroup(TpTransferirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(TpTransferirLayout.createSequentialGroup()
                                    .addComponent(jLabel17)
                                    .addGap(30, 30, 30)
                                    .addComponent(Tfdtransferir, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(TpTransferirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(TpTransferirLayout.createSequentialGroup()
                                        .addComponent(RdContato2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(LbContato2, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(TpTransferirLayout.createSequentialGroup()
                                        .addComponent(RdContato3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(LbContato3, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap(276, Short.MAX_VALUE))
        );
        TpTransferirLayout.setVerticalGroup(
            TpTransferirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TpTransferirLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(TpTransferirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(RdContato3)
                    .addGroup(TpTransferirLayout.createSequentialGroup()
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addGroup(TpTransferirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(LbContato2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RdContato2))
                        .addGap(83, 83, 83)
                        .addComponent(LbContato3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(108, 108, 108)
                .addGroup(TpTransferirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(Tfdtransferir, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 140, Short.MAX_VALUE)
                .addComponent(BtnConfirmaTransferir)
                .addGap(70, 70, 70))
        );

        PlPrincipal.addTab("TpTra", TpTransferir);

        getContentPane().add(PlPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(-60, 110, 900, 620));

        BtnServicos.setBackground(new java.awt.Color(255, 102, 0));
        BtnServicos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tela/serviço.png"))); // NOI18N
        BtnServicos.setText("Serviços");
        BtnServicos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnServicosActionPerformed(evt);
            }
        });
        getContentPane().add(BtnServicos, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 80, 110, 30));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel1.setText("Saldo");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 50, 32));

        BtnEntrar.setBackground(new java.awt.Color(255, 0, 0));
        BtnEntrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tela/conecte-se.png"))); // NOI18N
        BtnEntrar.setText("Acessar Minha Conta");
        BtnEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEntrarActionPerformed(evt);
            }
        });
        getContentPane().add(BtnEntrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 20, 220, -1));

        BtnSair.setBackground(new java.awt.Color(255, 0, 0));
        BtnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tela/sair.png"))); // NOI18N
        BtnSair.setText("Sair");
        BtnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSairActionPerformed(evt);
            }
        });
        getContentPane().add(BtnSair, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 20, 130, -1));

        LbSaldo.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        LbSaldo.setText("0");
        getContentPane().add(LbSaldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 50, 30));

        BtnRecarregar.setBackground(new java.awt.Color(255, 0, 0));
        BtnRecarregar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        BtnRecarregar.setText("Recarregue");
        BtnRecarregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRecarregarActionPerformed(evt);
            }
        });
        getContentPane().add(BtnRecarregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 120, 50));

        BtnConsumo.setBackground(new java.awt.Color(255, 102, 0));
        BtnConsumo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tela/grafico.png"))); // NOI18N
        BtnConsumo.setText("Consumo");
        BtnConsumo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnConsumoActionPerformed(evt);
            }
        });
        getContentPane().add(BtnConsumo, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, 120, 30));

        BtnTransferir.setBackground(new java.awt.Color(255, 102, 0));
        BtnTransferir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tela/transferir.png"))); // NOI18N
        BtnTransferir.setText("Transferir");
        BtnTransferir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnTransferirActionPerformed(evt);
            }
        });
        getContentPane().add(BtnTransferir, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 80, 120, 30));

        jLabel13.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        jLabel13.setText("Nome");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 60, -1, -1));

        jLabel14.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        jLabel14.setText("Número");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 80, -1, -1));

        LbNome.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        getContentPane().add(LbNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 60, 100, 20));

        LbNumero.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        getContentPane().add(LbNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 80, 80, 20));

        jLabel16.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        jLabel16.setText("R$");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 40, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnServicosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnServicosActionPerformed
        PlPrincipal.setSelectedIndex(2);
    }//GEN-LAST:event_BtnServicosActionPerformed

    private void BtnConsumoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnConsumoActionPerformed
        PlPrincipal.setSelectedIndex(0);

        int[] servicos = conta1.getServico();

        LbConsumoTotal.setText(Integer.toString(conta1.getConsumoTotal()));

        LbBitcallsTransferidos.setText(Integer.toString(conta1.getTransferir()));

        LbChamadaLocal.setText(Integer.toString(servicos[0]));

        LbChamadaEstadual.setText(Integer.toString(servicos[1]));

        LbChamadaInterEstado.setText(Integer.toString(servicos[2]));

        LbSms.setText(Integer.toString(servicos[3]));

        LbInternet.setText(Integer.toString(servicos[4]));
    }//GEN-LAST:event_BtnConsumoActionPerformed

    private void BtnRecarregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRecarregarActionPerformed
        PlPrincipal.setSelectedIndex(1);
    }//GEN-LAST:event_BtnRecarregarActionPerformed

    private void BtnEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEntrarActionPerformed
        conta1.setEstado(true);

        BtnSair.setVisible(true);
        BtnEntrar.setVisible(false);

        // Celular 1 - conta principal
        Celular celular1 = new Celular();
        ContaCelular conta1 = new ContaCelular();

        celular1.setNome("Pedro");
        celular1.setNumero(980564589);
        conta1.setNumero(celular1);

        LbNome.setText(celular1.getNome());

        LbNumero.setText(Integer.toString(celular1.getNumero()));

        LbSaldo.setText(Integer.toString(conta1.getBitcalls()));

        celular2.setNome("Maria");
        celular2.setNumero(940458287);
        conta2.setNumero(celular2);

        LbContato2.setText(celular2.getNome() + " " + celular2.getNumero());

        celular3.setNome("José");
        celular3.setNumero(945879281);
        conta3.setNumero(celular3);

        LbContato3.setText(celular3.getNome() + " " + celular3.getNumero());
    }//GEN-LAST:event_BtnEntrarActionPerformed

    private void BtnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSairActionPerformed
        conta1.setEstado(false);
        BtnSair.setVisible(false);
        BtnEntrar.setVisible(true);

        LbNome.setText("");
        LbNumero.setText("");

    }//GEN-LAST:event_BtnSairActionPerformed

    private void Btn10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn10ActionPerformed
        if (conta1.isEstado()) {
            conta1.setBitcalls(10);
            LbSaldo.setText(Integer.toString(conta1.getBitcalls()));
        }
    }//GEN-LAST:event_Btn10ActionPerformed

    private void Btn15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn15ActionPerformed
        if (conta1.isEstado()) {
            conta1.setBitcalls(15);
            LbSaldo.setText(Integer.toString(conta1.getBitcalls()));
        }

    }//GEN-LAST:event_Btn15ActionPerformed

    private void Btn25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn25ActionPerformed
        if (conta1.isEstado()) {
            conta1.setBitcalls(25);
            LbSaldo.setText(Integer.toString(conta1.getBitcalls()));
        }

    }//GEN-LAST:event_Btn25ActionPerformed

    private void Btn50ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn50ActionPerformed
        if (conta1.isEstado()) {
            conta1.setBitcalls(50);
            LbSaldo.setText(Integer.toString(conta1.getBitcalls()));
        }

    }//GEN-LAST:event_Btn50ActionPerformed

    private void BtnSmsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSmsActionPerformed
        if (conta1.isEstado()) {
            conta1.setServico(4);
            if (conta1.getBitcalls() > 1) {
                JOptionPane.showMessageDialog(null, "SMS enviado");
            } else {
                JOptionPane.showMessageDialog(null, "Bitcalls insuficientes");
            }

            LbSaldo.setText(Integer.toString(conta1.getBitcalls()));
        }
    }//GEN-LAST:event_BtnSmsActionPerformed

    private void BtnChamadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnChamadaActionPerformed
        if (conta1.isEstado()) {
            conta1.setServico(1);
            if (conta1.getBitcalls() > 2) {
                JOptionPane.showMessageDialog(null, "Chamada local realizada");
            } else {
                JOptionPane.showMessageDialog(null, "Bitcalls insuficientes");
            }

            LbSaldo.setText(Integer.toString(conta1.getBitcalls()));
        }

    }//GEN-LAST:event_BtnChamadaActionPerformed

    private void BtnChamadaDDDEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnChamadaDDDEstadoActionPerformed
        if (conta1.isEstado()) {
            conta1.setServico(2);
            if (conta1.getBitcalls() > 3) {
                JOptionPane.showMessageDialog(null, "Chamada DDD estadual realizada");
            } else {
                JOptionPane.showMessageDialog(null, "Bitcalls insuficientes");
            }

            LbSaldo.setText(Integer.toString(conta1.getBitcalls()));
        }
    }//GEN-LAST:event_BtnChamadaDDDEstadoActionPerformed

    private void BtnChamadaDDDEstadoForaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnChamadaDDDEstadoForaActionPerformed
        if (conta1.isEstado()) {
            conta1.setServico(3);
            if (conta1.getBitcalls() > 5) {
                JOptionPane.showMessageDialog(null, "Chamada DDD para fora do estado realizada");
            } else {
                JOptionPane.showMessageDialog(null, "Bitcalls insuficientes");
            }

            LbSaldo.setText(Integer.toString(conta1.getBitcalls()));
        }
    }//GEN-LAST:event_BtnChamadaDDDEstadoForaActionPerformed

    private void BtnInternetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnInternetActionPerformed
        if (conta1.isEstado()) {
            conta1.setServico(5);
            if (conta1.getBitcalls() > 5) {
                JOptionPane.showMessageDialog(null, "Internet 4G para o dia todo");
            } else {
                JOptionPane.showMessageDialog(null, "Bitcalls insuficientes");
            }

            LbSaldo.setText(Integer.toString(conta1.getBitcalls()));
        }
    }//GEN-LAST:event_BtnInternetActionPerformed

    private void BtnTransferirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnTransferirActionPerformed
        PlPrincipal.setSelectedIndex(3);

        Tfdtransferir.setText("");
        Tfdtransferir.requestFocus();
    }//GEN-LAST:event_BtnTransferirActionPerformed

    private void BtnConfirmaTransferirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnConfirmaTransferirActionPerformed
        if (conta1.isEstado()) {
            int qtdBitcalls = Integer.parseInt(Tfdtransferir.getText());

            if (conta1.getBitcalls() > qtdBitcalls) {
                JOptionPane.showMessageDialog(null, "Bitcalls transferidos");
            } else {
                JOptionPane.showMessageDialog(null, "Bitcalls insuficientes");
            }
            
            if (RdContato2.isSelected() && RdContato3.isSelected()) {
                conta1.setTransferir(qtdBitcalls, conta2);
                conta1.setTransferir(qtdBitcalls, conta3);

            } else if (RdContato3.isSelected()) {
                conta1.setTransferir(qtdBitcalls, conta3);

            } else if (RdContato2.isSelected()) {
                conta1.setTransferir(qtdBitcalls, conta2);
            }

            LbSaldo.setText(Integer.toString(conta1.getBitcalls()));
        }

    }//GEN-LAST:event_BtnConfirmaTransferirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmTela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn10;
    private javax.swing.JButton Btn15;
    private javax.swing.JButton Btn25;
    private javax.swing.JButton Btn50;
    private javax.swing.JButton BtnChamada;
    private javax.swing.JButton BtnChamadaDDDEstado;
    private javax.swing.JButton BtnChamadaDDDEstadoFora;
    private javax.swing.JButton BtnConfirmaTransferir;
    private javax.swing.JButton BtnConsumo;
    private javax.swing.JButton BtnEntrar;
    private javax.swing.JButton BtnInternet;
    private javax.swing.JButton BtnRecarregar;
    private javax.swing.JButton BtnSair;
    private javax.swing.JButton BtnServicos;
    private javax.swing.JButton BtnSms;
    private javax.swing.JButton BtnTransferir;
    private javax.swing.JLabel LbBitcallsTransferidos;
    private javax.swing.JLabel LbChamadaEstadual;
    private javax.swing.JLabel LbChamadaInterEstado;
    private javax.swing.JLabel LbChamadaLocal;
    private javax.swing.JLabel LbConsumoTotal;
    private javax.swing.JLabel LbContato2;
    private javax.swing.JLabel LbContato3;
    private javax.swing.JLabel LbInternet;
    private javax.swing.JLabel LbNome;
    private javax.swing.JLabel LbNumero;
    private javax.swing.JLabel LbSaldo;
    private javax.swing.JLabel LbSms;
    private javax.swing.JTabbedPane PlPrincipal;
    private javax.swing.JRadioButton RdContato2;
    private javax.swing.JRadioButton RdContato3;
    private javax.swing.JTextField Tfdtransferir;
    private javax.swing.JPanel TpConsumo;
    private javax.swing.JPanel TpRecarregar;
    private javax.swing.JPanel TpServicos;
    private javax.swing.JPanel TpTransferir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
